name: "CI - Pull Request"

on:
  pull_request:
    paths-ignore:
      - '**/*.md'
      - 'LICENSE*'

permissions:
  contents: read

concurrency:
  group: ci-pr-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    uses: ./.github/workflows/test.yaml
    permissions:
      contents: read

  e2e:
    if: ${{ !github.event.pull_request.draft }}
    uses: ./.github/workflows/e2e.yaml
    permissions:
      contents: read

  build-image:
    name: Build Image (No Push)
    needs: [test]
    uses: ./.github/workflows/ghcr-build-push.yaml
    with:
      push: false
      platforms: linux/amd64
      sbom: false
      provenance: false
    permissions:
      contents: read
